trigger:
  - main 

pool:
  vmImage: ubuntu-latest # This specifies the virtual machine image to use for running the pipeline. Replace `ubuntu-latest` with the desired image.

steps:
  - script: |
      echo "Hello, world!" # This is an example script step. Replace this with your own script.
    displayName: 'Run a script' # This is the display name for the step. Replace this with a description of what the step does.
